name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Build and rune Dev Container
              uses: devcontainers/ci@v0.3
              with:
                imageName: ghcr.io/
                runCmd: npm test