name: Deploy
on:
  push:
    branches:
      - probot-setup
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
    deploy:
        name: deploy-gcf
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - id: 'auth'
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  

            - name: Set up Cloud SDK
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                project_id: ${{ secrets.GCP_PROJECT_ID }}

            - name: Deploy to GCF
              run: |
                gcloud functions deploy trackpoint-github-gcf \
                --runtime nodejs18 \
                --allow-unauthenticated \
                --trigger-http \
                --entry-point probotApp \
                --region europe-west3 \
                --set-secrets=APP_ID=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/APP_ID:latest \
                --set-secrets=PRIVATE_KEY=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/PRIVATE_KEY:latest \
                --set-secrets=WEBHOOK_SECRET=projects/${{ secrets.GCP_PROJECT_ID }}/secrets/WEBHOOK_SECRET:latest \
                --service-account=trackpoint-github-app@trackpointdb.iam.gserviceaccount.com
